name: placez
description: Placez App

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  # System
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1

  # Firebase
  firebase_core: ^2.4.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localizations/
