name: placez
description: Placez App

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  # System
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  go_router: ^5.2.4
  flutter_native_splash: ^2.2.16

  # Network
  internet_connection_checker: ^1.0.0+1

  # Firebase
  firebase_core: ^2.4.0

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localizations/
